#!/bin/sh
set -e
set -u

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "postgres" <<-EOSQL
	CREATE USER $AUTHN_PG_USER WITH PASSWORD '$AUTHN_PG_PASSWORD';
	CREATE DATABASE $AUTHN_PG_DB;
	GRANT ALL PRIVILEGES ON DATABASE $AUTHN_PG_DB TO $AUTHN_PG_USER;

	CREATE USER $USER_PG_USER WITH PASSWORD '$USER_PG_PASSWORD';
	CREATE DATABASE $USER_PG_DB;
	GRANT ALL PRIVILEGES ON DATABASE $USER_PG_DB TO $USER_PG_USER;

	CREATE USER $CHAT_PG_USER WITH PASSWORD '$CHAT_PG_PASSWORD';
	CREATE DATABASE $CHAT_PG_DB;
	GRANT ALL PRIVILEGES ON DATABASE $CHAT_PG_DB TO $CHAT_PG_USER;

	CREATE USER $PLAYLIST_PG_USER WITH PASSWORD '$PLAYLIST_PG_PASSWORD';
	CREATE DATABASE $PLAYLIST_PG_DB;
	GRANT ALL PRIVILEGES ON DATABASE $PLAYLIST_PG_DB TO $PLAYLIST_PG_USER;

	CREATE USER $CHAT_AUTHZ_PG_USER WITH PASSWORD '$CHAT_AUTHZ_PG_PASSWORD';
	CREATE DATABASE $CHAT_AUTHZ_PG_DB;
	GRANT ALL PRIVILEGES ON DATABASE $CHAT_AUTHZ_PG_DB TO $CHAT_AUTHZ_PG_USER;
EOSQL

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$AUTHN_PG_DB" <<-EOSQL
	GRANT USAGE, CREATE ON SCHEMA public TO $AUTHN_PG_USER;
	ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL ON TABLES TO $AUTHN_PG_USER;
	ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL ON SEQUENCES TO $AUTHN_PG_USER;
EOSQL

# USER
psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$USER_PG_DB" <<-EOSQL
	GRANT USAGE, CREATE ON SCHEMA public TO $USER_PG_USER;
	ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL ON TABLES TO $USER_PG_USER;
	ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL ON SEQUENCES TO $USER_PG_USER;
EOSQL

# CHAT
psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$CHAT_PG_DB" <<-EOSQL
	GRANT USAGE, CREATE ON SCHEMA public TO $CHAT_PG_USER;
	ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL ON TABLES TO $CHAT_PG_USER;
	ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL ON SEQUENCES TO $CHAT_PG_USER;
EOSQL

# PLAYLIST
psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$PLAYLIST_PG_DB" <<-EOSQL
	GRANT USAGE, CREATE ON SCHEMA public TO $PLAYLIST_PG_USER;
	ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL ON TABLES TO $PLAYLIST_PG_USER;
	ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL ON SEQUENCES TO $PLAYLIST_PG_USER;
EOSQL

# CHAT_AUTHZ
psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$CHAT_AUTHZ_PG_DB" <<-EOSQL
	GRANT USAGE, CREATE ON SCHEMA public TO $CHAT_AUTHZ_PG_USER;
	ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL ON TABLES TO $CHAT_AUTHZ_PG_USER;
	ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL ON SEQUENCES TO $CHAT_AUTHZ_PG_USER;
EOSQL