syntax = "proto3";

package cinemaroom.user.v1.request;

option php_namespace = "GRPC\\Services\\Users\\v1";
option php_metadata_namespace = "GRPC\\ProtobufMetadata\\Users\\v1";

import "cinemaroom/common/v1/message.proto";
import "cinemaroom/user/v1/message.proto";

message RegisterRequest {
  string username = 1;
}

message GetRequest {
  common.v1.message.Uuid id = 1;
}

message EditRequest {
  common.v1.message.Uuid id = 1;
  optional string username = 2;
  optional user.v1.message.Avatar avatar = 3;
  optional string bio = 4;
}