services:
  gateway:
    profiles:
      - app
      - backend
    build:
      context: ./
      dockerfile: ./.docker/gateway/Dockerfile
      target: app_php_dev
      args:
        - ALPINE_VERSION
        - PHP_VERSION
        - COMPOSER_VERSION
        - PHP_EXT_INSTALLER_VERSION
        - PROTOC_VERSION
        - UID
        - GID
    volumes:
      - ./services/gateway:/app
      - ./lib/proto:/lib/proto
    ports:
      - ${NETWORK_INTERFACE:-127.0.0.1}:${GATEWAY_PORT:-8000}:9501
    networks:
      - cinemaroom
    env_file: ./lib/.common.env
    entrypoint: entrypoint.sh

  user:
    build:
      context: ./
      dockerfile: ./.docker/user/Dockerfile
      target: app_php_dev
      args:
        - ALPINE_VERSION
        - PHP_VERSION
        - COMPOSER_VERSION
        - PHP_EXT_INSTALLER_VERSION
        - ROADRUNNER_VERSION
        - PROTOC_VERSION
        - GOLANG_VERSION
        - UID
        - GID
    volumes:
      - ./services/user:/app
      - ./lib/proto:/lib/proto
    ports:
      - ${NETWORK_INTERFACE:-127.0.0.1}:${USER_SERVICE_PORT:-8002}:8080
    networks:
      - cinemaroom
    env_file: ./lib/.common.env
    environment:
      RR_CONFIG_FILE: ${USER_RR_CONFIG_FILE}
    entrypoint: entrypoint.sh

  authn:
    build:
      context: ./
      dockerfile: ./.docker/authn/Dockerfile
      target: app_go_dev
      args:
        - GOLANG_VERSION
        - ALPINE_VERSION
        - PROTOC_VERSION
        - UID
        - GID
    networks:
      - cinemaroom
    ports:
      - ${NETWORK_INTERFACE:-127.0.0.1}:${AUTHN_PORT:-8003}:8080
    volumes:
      - ./services/authn:/app
      - go-mod-cache:/go/pkg/mod
    entrypoint: entrypoint.sh

  chat:
    build:
      context: ./
      dockerfile: ./.docker/chat/Dockerfile
      target: app_php_composer
      args:
        - ALPINE_VERSION
        - PHP_VERSION
        - COMPOSER_VERSION
        - PHP_EXT_INSTALLER_VERSION
        - ROADRUNNER_VERSION
        - PROTOC_VERSION
        - GOLANG_VERSION
        - UID
        - GID
    volumes:
      - ./services/chat:/app
      - ./lib/proto:/lib/proto
    ports:
      - ${NETWORK_INTERFACE:-127.0.0.1}:${CHAT_SERVICE_PORT:-8003}:8080
    networks:
      - cinemaroom
    env_file: ./lib/.common.env
    tty: true
  #    entrypoint: entrypoint.sh

  playlist:
    build:
      context: ./
      dockerfile: ./.docker/playlist/Dockerfile
      target: app_php_composer
      args:
        - ALPINE_VERSION
        - PHP_VERSION
        - COMPOSER_VERSION
        - PHP_EXT_INSTALLER_VERSION
        - ROADRUNNER_VERSION
        - PROTOC_VERSION
        - GOLANG_VERSION
        - UID
        - GID
    volumes:
      - ./services/playlist:/app
      - ./lib/proto:/lib/proto
    ports:
      - ${NETWORK_INTERFACE:-127.0.0.1}:${PLAYLIST_SERVICE_PORT:-8004}:8080
    networks:
      - cinemaroom
    env_file: ./lib/.common.env
    tty: true
#    entrypoint: entrypoint.sh

networks:
  cinemaroom:
    name: cinemaroom

volumes:
  go-mod-cache:
    