x-php: &php
    build:
        context: ./
        dockerfile: ./.docker/php/Dockerfile
        target: app_php_test
        args:
            - ALPINE_VERSION
            - PHP_VERSION
            - COMPOSER_VERSION
            - PHP_EXT_INSTALLER_VERSION
            - GOLANG_VERSION
            - USER_NAME
            - GROUP_NAME
            - UID
            - GID
    env_file: .app.env
    networks:
        - default
    depends_on:
        db:
            condition: service_healthy
        cache:
            condition: service_healthy

services:
    app:
        <<: *php
        command: php -d variables_order=EGPCS /app/artisan octane:start --server=roadrunner --host=0.0.0.0 --rpc-port=6001 --port=8080

    utils:
        <<: *php
        container_name: utils
        command: supercronic /etc/supercronic/crontab

    db:
        image: postgres:${POSTGRES_VERSION:?}
        networks:
            - default
        environment:
            POSTGRES_USER: ${DB_USER:?}
            POSTGRES_PASSWORD: ${DB_PASSWORD:?}
            POSTGRES_DB: ${DB_DATABASE:?}
        healthcheck:
            test: [ 'CMD-SHELL', 'pg_isready -U ${DB_USER} -d ${DB_DATABASE}' ]
            start_period: 2s
            retries: 10
            interval: 2s
            timeout: 5s

    cache:
        image: redis:${REDIS_VERSION:?}
        networks:
            - default
        healthcheck:
            test: [ 'CMD-SHELL', 'redis-cli ping' ]
            interval: 500ms
            timeout: 1s

networks:
    default:


