x-php: &php
  build:
    target: app_php_dev
  volumes:
    - ./:/app
    - ./.app.env:/app/.env

services:
  app:
    <<: *php
    env_file: !reset null
    extra_hosts:
      - host.docker.internal:host-gateway
    volumes: !reset [ ]
#    tty: true
#    entrypoint: !reset null

  utils:
    <<: *php
    container_name: cinemaroom-utils
    env_file: !reset null

  buggregator:
    image: ghcr.io/buggregator/server:dev
    ports:
      - ${NETWORK_INTERFACE:-127.0.0.1}:${BR_HTTP_DUMPS_PORT:-8000}:8000
      - ${NETWORK_INTERFACE:-127.0.0.1}:${BR_SMTP_PORT:-1025}:1025
      - ${NETWORK_INTERFACE:-127.0.0.1}:${BR_VAR_DUMPER_PORT:-9912}:9912
      - ${NETWORK_INTERFACE:-127.0.0.1}:${BR_MONOLOG_PORT:-9913}:9913
    depends_on:
      app:
        condition: service_started
      utils:
        condition: service_started

  db:
    volumes: !override
      - db-data:/var/lib/postgresql/data/
      - ./.docker/postgres/dump/:/dump/

  cache:
    volumes: !override
      - cache-data:/data/

#    minio:
#        image: quay.io/minio/minio:${MINIO_VERSION:?}
#        environment:
#            MINIO_ROOT_USER: ${MINIO_ROOT_USER:?}
#            MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD:?}
#        ports:
#            - ${NETWORK_INTERFACE:-127.0.0.1}:${MINIO_API_PORT:-9000}:9000
#            - ${NETWORK_INTERFACE:-127.0.0.1}:${MINIO_UI_PORT:-9001}:9001
#        volumes:
#            - minio-data:/data
#        command: server --console-address ":9001" /data
#        healthcheck:
#            test: [ "CMD", "mc", "ready", "local" ]
#            interval: 5s
#            timeout: 5s
#            retries: 5

volumes: !override
  db-data:
  cache-data:
  minio-data:
