syntax = "proto3";

package cinemaroom.authn.v1.service;

option php_namespace = "GRPC\\Services\\Authn\\v1";
option php_metadata_namespace = "GRPC\\ProtobufMetadata\\Authn\\v1";

import "cinemaroom/authn/v1/request.proto";
import "cinemaroom/authn/v1/response.proto";

service AuthnService {
  rpc Register (authn.v1.request.RegisterRequest) returns (authn.v1.response.RegisterResponse);
  rpc Login (authn.v1.request.LoginRequest) returns (authn.v1.response.LoginResponse);
  rpc Refresh (authn.v1.request.RefreshRequest) returns (authn.v1.response.RefreshResponse);
  rpc Logout (authn.v1.request.LogoutRequest) returns (authn.v1.response.LogoutResponse);
  rpc Edit (authn.v1.request.EditRequest) returns (authn.v1.response.EditResponse);
}
