syntax = "proto3";

package cinemaroom.chat.v1.request;

option php_namespace = "GRPC\\Services\\Chat\\v1";
option php_metadata_namespace = "GRPC\\ProtobufMetadata\\Chat\\v1";

import "cinemaroom/common/v1/message.proto";

message CreateRoomRequest {
  string name = 1;
  string description = 2;
}

message UpdateRoomRequest {
  common.v1.message.Uuid room_id = 1;
  optional string name = 2;
  optional string description = 3;
}

message ListRoomsRequest {
  string limit = 1;
  string offset = 2;
}

message ShowRoomRequest {
  common.v1.message.Uuid room_id = 1;
}

message SendMessageRequest {
  common.v1.message.Uuid room_id = 1;
  string content = 2;
}

message GetMessagesRequest {
  common.v1.message.Uuid room_id = 1;
}
