version: "3"

server:
  command: "php public/index.php"
  env:
    - APP_RUNTIME: Baldinof\RoadRunnerBundle\Runtime\Runtime

grpc:
  listen: "tcp://0.0.0.0:9001"
  proto:
    - "/lib/proto/cinemaroom/user/v1/service.proto"
  pool:
    debug: true
    num_workers: 1

logs:
  mode: development
  channels:
    http:
      level: debug
    server:
      level: info
      mode: raw
    metrics:
      level: debug

rpc:
  listen: tcp://127.0.0.1:6001
